export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_LOGOUT="AUTH_LOGOUT";
export const UPLOAD_CREATE="UPLOAD_CREATE";
export const UPLOAD_UPDATE="UPLOAD_UPDATE";
export const UPLOAD_DELETE="UPLOAD_DELETE";
export const UPLOAD_CREATE_FAILL="UPLOAD_CREATE_FAILL";
export const UPLOAD_CREATE_SUCCESS="UPLOAD_CREATE_SUCCESS";

export const GET_UPLOADED_NFTS_SUCCESS = "GET_UPLOADED_NFTS_SUCCESS";
export const GET_UPLOADED_NFTS_FAIL = "GET_UPLOADED_NFTS_FAIL";

export const UPLOAD_CREATE_BID = "UPLOAD_CREATE_BID";
export const UPLOAD_CREATE_BID_FAIL = "UPLOAD_CREATE_BID_FAIL";
export const UPLOAD_CREATE_BID_SUCCESS = "UPLOAD_CREATE_BID_SUCCESS";

export const GET_NFT_BID_SUCCESS = "GET_NFT_BID_SUCCESS";
export const GET_NFT_BID_FAIL = "GET_NFT_BID_FAIL";